cc_binary (
    name = 'hash_function_test',
    srcs = 'hash_function_test.cpp',
    deps = [
        '//bloom_filter/hash_utils:ap_hash',
        '//bloom_filter/hash_utils:bkdr_hash',
        '//bloom_filter/hash_utils:bp_hash',
        '//bloom_filter/hash_utils:dek_hash',
        '//bloom_filter/hash_utils:djb_hash',
        '//bloom_filter/hash_utils:elf_hash',
        '//bloom_filter/hash_utils:fnv_hash',
        '//bloom_filter/hash_utils:js_hash',
        '//bloom_filter/hash_utils:pjw_hash',
        '//bloom_filter/hash_utils:rs_hash',
        '//bloom_filter/hash_utils:sdbm_hash',
    ],
)
