cc_library (
    name = 'ap_hash',
    srcs = 'ap_hash.cpp',
    deps = [],
)

cc_library (
    name = 'bkdr_hash',
    srcs = 'bkdr_hash.cpp',
    deps = [],
)

cc_library (
    name = 'bp_hash',
    srcs = 'bp_hash.cpp',
    deps = [],
)

cc_library (
    name = 'dek_hash',
    srcs = 'dek_hash.cpp',
    deps = [],
)

cc_library (
    name = 'djb_hash',
    srcs = 'djb_hash.cpp',
    deps = [],
)
cc_library (
    name = 'elf_hash',
    srcs = 'elf_hash.cpp',
    deps = [],
)

cc_library (
    name = 'fnv_hash',
    srcs = 'fnv_hash.cpp',
    deps = [],
)

cc_library (
    name = 'js_hash',
    srcs = 'js_hash.cpp',
    deps = [],
)

cc_library (
    name = 'pjw_hash',
    srcs = 'pjw_hash.cpp',
    deps = [],
)

cc_library (
    name = 'rs_hash',
    srcs = 'rs_hash.cpp',
    deps = [],
)

cc_library (
    name = 'sdbm_hash',
    srcs = 'sdbm_hash.cpp',
    deps = [],
)

